version: '2'
services:
  mongodb:
    build:
      context: './mongo'
    volumes:
      - ./mongo/volumes/db:/data/db
    networks:
      vpcbr:
        ipv4_address: 10.1.0.4
  elasticsearch:
    build:
      context: './elasticsearch'
    volumes:
      - ./elasticsearch/volumes/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      vpcbr:
        ipv4_address: 10.1.0.5
  graylog:
    build:
      context: './graylog'
    volumes:
      - ./graylog/volumes/journal:/usr/share/graylog/data/journal
      - ./graylog/volumes/config:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=password123456789!
      - GRAYLOG_ROOT_PASSWORD_SHA2=808e92f675e72700837eec448b57b602c9d9762ca713de36ad378ed1e4a0262f
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    user: root

    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      vpcbr:
        ipv4_address: 10.1.0.7
networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
